name: Fetch Option Data
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Pyhton
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Fetch Option Data
        run: python my_script.py